### ISSUE TITLE
[PE-D][Tester B] swap-task does not work when swapped with a task number that does not exist

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T10-1/tp#138] opened 2022-10-29 03:40 UTC
![image.png](https://raw.githubusercontent.com/Kennethsim2000/ped/main/files/b46d18df-380a-4259-a45b-a260e4944143.png)

When i specify a task number that does not exist, no error message is printed. It just remains in the same position

swap-task m/cs2103t ts/1 4 does not work when i only have 3 tasks-->no error message printed

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Kennethsim2000/ped#8

**Comment by cheeheng** [comment] 2022-10-29 15:43
Duplicate of #136

**Closed by cheeheng** 2022-10-29 15:43 UTC
